# Generated by Django 2.2.10 on 2020-07-08 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0027_auto_20200428_0711'),
        ('formlibrary', '0008_delete_trainingattendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='household',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='individual',
            old_name='household',
            new_name='household_id',
        ),
        migrations.RenameField(
            model_name='individual',
            old_name='father_name',
            new_name='id_number',
        ),
        migrations.RenameField(
            model_name='individual',
            old_name='gender',
            new_name='id_type',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='distribution',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='program',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='training',
        ),
        migrations.AddField(
            model_name='household',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Country'),
        ),
        migrations.AddField(
            model_name='household',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='household',
            name='individuals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formlibrary.Individual'),
        ),
        migrations.AddField(
            model_name='household',
            name='postal_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='primary_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='secondary_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='head_of_household',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='individual',
            name='primary_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='secondary_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
