# Generated by Django 2.2.10 on 2020-07-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0009_auto_20200708_0831'),
        ('formlibrary', '0009_merge_20200620_0127'),
    ]

    operations = [
    ]
